Feature/ryu todo UI
indigo-sti-front-ojt/training pull request #17
Opened 2022-07-01 02:26 UTC by ReiRyuSTI

## チケットへのリンク
* https://sios-tech.atlassian.net/browse/IN-2637?atlOrigin=eyJpIjoiODAzMTJlODY3ZjYzNDM4NDhmNGNiZDY1NTA4MThhNjAiLCJwIjoiaiJ9
## やったこと
* Material UIv5　インストール
* TODOの画面デザイン
* Propsの修正

## やらないこと
* なし

## できるようになること（ユーザ目線）
* TODOにデザインがついた

## できなくなること（ユーザ目線）
* なし

## 動作確認
* ローカルで確認

## その他
* v4 と v5でインストールコマンドと命名が変わっている
## 影響する機能
* なし

2022-07-01 02:50 UTC, yu-arimura requested changes

2022-07-01 02:50 UTC, yu-arimura commented on react_training_ryu/src/components/ToDoInput.tsx
> +        container
この3つは必要ない気がします
```
        justifyContent="center"
        alignContent="center"
        container
```

2022-07-01 02:50 UTC, yu-arimura commented on react_training_ryu/src/components/ToDoItem.tsx
> +      item
個人的な好き嫌いの問題なんですが、containerとitemを一生に使わない方が可読性が上がる気がします

```
<Grid container>
  <Grid container item>
    :
  </Grid>
</Grid>

↓

<Grid container>
 <Grid item>
    <Grid container>
     <Grid item>
     </Grid>
    </Grid>
 </Grid>
</Grid>

```

2022-07-01 02:50 UTC, yu-arimura commented on react_training_ryu/src/components/ToDoList.tsx
> +          spacing={2}
<Grid container>の中に<Grid item>を入れないとflex-boxが正常に動作しない気がします

2022-07-01 05:46 UTC, ReiRyuSTI commented on react_training_ryu/src/components/ToDoList.tsx
> +          spacing={2}
ここは子コンポーネントでitemを呼び出している形に修正しました。

2022-07-01 05:47 UTC, ReiRyuSTI commented on react_training_ryu/src/components/ToDoInput.tsx
> +        container
GridではなくBoxでフレックスを使用するに変更します

2022-07-01 05:47 UTC, ReiRyuSTI commented on react_training_ryu/src/components/ToDoItem.tsx
> +      item
今後は分割して書くように修正します

2022-07-01 07:43 UTC, yu-arimura approved these changes
今日の1on1でgridの組み方みたいなの説明しますね

2022-07-04 00:10 UTC, y-okada-public approved these changes

2022-07-04 00:58 UTC, merged